---
- name: Deploy Aplicacao de Mensagens
  hosts: localhost
  become: true
  become_method: sudo
  become_user: root

  vars_files:
    - group_vars/vars.yml

  tasks:
    - name: Garantir que o cache do apt está atualizado
      apt:
        update_cache: yes

    - name: Instalar Docker e Docker Compose
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Garantir que o serviço Docker está em execução
      service:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório do projeto
      file:
        path: /opt/messenger_app
        state: directory
        mode: '0755'

    - name: Copiar arquivos do projeto para o servidor
      copy:
        src: "{{ item }}"
        dest: /opt/messenger_app/
      with_items:
        - cliente.py
        - servidor.py
        - messenger.proto
        - Dockerfile.cliente
        - Dockerfile.servidor
        - docker-compose.yml
        - init_db.sql
        - requirements.txt

    - name: Iniciar contêineres Docker
      shell: docker-compose up --build -d
      args:
        chdir: /opt/messenger_app

    - name: Verificar se o contêiner do banco de dados está em execução
      community.docker.docker_container_info:
        name: db
      register: db_status_info

    - name: Verificar se o contêiner do servidor está em execução
      community.docker.docker_container_info:
        name: servidor
      register: servidor_status_info

    - name: Verificar se o contêiner do cliente está em execução
      community.docker.docker_container_info:
        name: cliente
      register: cliente_status_info
